# Solid Node - generated by `solid import-step`

"""Parts scaffolded from 'ORCA_v1.step' by `solid import-step`.

Generated once; edit freely -- running the command again
refuses to overwrite this file (see docs/cli.rst).
"""

from solid_node.node import StepNode


class Part42TeethV9(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '42_teeth v9'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5

class SOLID(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class CarpalsSkinV30(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'CarpalsSkin v30'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RTopTowerV11(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'R-TopTower v11'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class BottomTowerV74(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'BottomTower v74'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01CASEMDUMMY(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_CASE_M_DUMMY'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01CASEFDUMMY(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_CASE_F_DUMMY'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01CASEBDUMMY(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_CASE_B_DUMMY'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01HORNDUMMY(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_HORN_DUMMY'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01LEDCAP2DUMMY(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_LED_CAP2_DUMMY'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01HORNIDLE2DUMMY(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_HORN_IDLE2_DUMMY'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01IDLECAPDUMMY(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_IDLE_CAP_DUMMY'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class B3BEH(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'B3B-EH'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class BaseSpoolV21(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'BaseSpool v21'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RatchetV6(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'Ratchet v6'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SpoolCoverV13(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SpoolCover v13'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part90591A265ZincPlatedSteelHexNut(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '90591A265_Zinc-Plated Steel Hex Nut'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part91239A703ButtonHeadHexDriveScrew(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '91239A703_Button Head Hex Drive Screw'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part93475A195_18_8StainlessSteelWasher(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '93475A195_18-8 Stainless Steel Washer'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part97763A408_18_8StainlessSteelButtonHeadHexDriveScrews(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '97763A408_18-8 Stainless Steel Button Head Hex Drive Screws'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class BaseSpoolV21_2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'BaseSpool v21'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class BaseSpoolV21_3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'BaseSpool v21'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class BaseSpoolV21_4(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'BaseSpool v21'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC11B01CASEMDUMMY(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC11_B01_CASE_M_DUMMY'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC11B01CASEFDUMMY(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC11_B01_CASE_F_DUMMY'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class COMPOUND(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'COMPOUND'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_4(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_5(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_4(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_6(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC11A01WINLED(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC11_A01_WIN_LED'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_5(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_7(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class MDC11A01IDLER(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'M_DC11_A01_IDLER'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_6(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_8(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class MDC11A01IDLERCAP(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'M_DC11_A01_IDLER_CAP'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_7(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_9(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_8(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_10(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class MDC11A01HORN(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'M_DC11_A01_HORN'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_9(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_11(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class B3BEH_2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'B3B-EH'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class EHR3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'EHR-3'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class PulleyBaseV9(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'Pulley_Base v9'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part91294A004BlackOxideAlloySteelHexDriveFlatHeadScrew(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '91294A004_Black-Oxide Alloy Steel Hex Drive Flat Head Screw'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part4x8x3V3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '4x8x3 v3'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part23TeethNewV2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '23_teeth_new v2'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class HullV32(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'Hull v32'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01CASEMDUMMYMirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_CASE_M_DUMMY(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01CASEFDUMMYMirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_CASE_F_DUMMY(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01CASEBDUMMYMirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_CASE_B_DUMMY(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01HORNDUMMYMirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_HORN_DUMMY(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01LEDCAP2DUMMYMirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_LED_CAP2_DUMMY(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_10(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_12(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_11(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_13(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01HORNIDLE2DUMMYMirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_HORN_IDLE2_DUMMY(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01IDLECAPDUMMYMirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_IDLE_CAP_DUMMY(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class B3BEHMirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'B3B-EH(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RatchetWBCDV2Mirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'Ratchet_WBCD v2(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RatchetRingCombinedV8Mirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'RatchetRing-combined v8(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_14(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SpoolOutWBCDV8Mirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SpoolOut_WBCD v8(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part90591A265ZincPlatedSteelHexNutMirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '90591A265_Zinc-Plated Steel Hex Nut(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part91239A703ButtonHeadHexDriveScrewMirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '91239A703_Button Head Hex Drive Screw(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part93475A195_18_8StainlessSteelWasherMirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '93475A195_18-8 Stainless Steel Washer(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part97763A408_18_8StainlessSteelButtonHeadHexDriveScrewsMirror2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '97763A408_18-8 Stainless Steel Button Head Hex Drive Screws(Mirror) (2)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01CASEMDUMMYMirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_CASE_M_DUMMY(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01CASEFDUMMYMirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_CASE_F_DUMMY(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01CASEBDUMMYMirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_CASE_B_DUMMY(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01HORNDUMMYMirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_HORN_DUMMY(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01LEDCAP2DUMMYMirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_LED_CAP2_DUMMY(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_12(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_15(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_13(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_16(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01HORNIDLE2DUMMYMirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_HORN_IDLE2_DUMMY(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01IDLECAPDUMMYMirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_IDLE_CAP_DUMMY(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class B3BEHMirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'B3B-EH(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RatchetWBCDV2Mirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'Ratchet_WBCD v2(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RatchetRingCombinedV8Mirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'RatchetRing-combined v8(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_17(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SpoolOutWBCDV8Mirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SpoolOut_WBCD v8(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part90591A265ZincPlatedSteelHexNutMirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '90591A265_Zinc-Plated Steel Hex Nut(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part91239A703ButtonHeadHexDriveScrewMirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '91239A703_Button Head Hex Drive Screw(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part93475A195_18_8StainlessSteelWasherMirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '93475A195_18-8 Stainless Steel Washer(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part97763A408_18_8StainlessSteelButtonHeadHexDriveScrewsMirror3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '97763A408_18-8 Stainless Steel Button Head Hex Drive Screws(Mirror) (3)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01CASEMDUMMYMirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_CASE_M_DUMMY(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01CASEFDUMMYMirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_CASE_F_DUMMY(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01CASEBDUMMYMirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_CASE_B_DUMMY(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01HORNDUMMYMirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_HORN_DUMMY(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01LEDCAP2DUMMYMirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_LED_CAP2_DUMMY(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_14(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_18(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SHELL_15(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SHELL'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_19(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01HORNIDLE2DUMMYMirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_HORN_IDLE2_DUMMY(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DC15A01IDLECAPDUMMYMirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DC15_A01_IDLE_CAP_DUMMY(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class B3BEHMirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'B3B-EH(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RatchetWBCDV2Mirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'Ratchet_WBCD v2(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RatchetRingCombinedV8Mirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'RatchetRing-combined v8(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SOLID_20(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SOLID'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class SpoolOutWBCDV8Mirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'SpoolOut_WBCD v8(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part90591A265ZincPlatedSteelHexNutMirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '90591A265_Zinc-Plated Steel Hex Nut(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part91239A703ButtonHeadHexDriveScrewMirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '91239A703_Button Head Hex Drive Screw(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part93475A195_18_8StainlessSteelWasherMirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '93475A195_18-8 Stainless Steel Washer(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part97763A408_18_8StainlessSteelButtonHeadHexDriveScrewsMirror2Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '97763A408_18-8 Stainless Steel Button Head Hex Drive Screws(Mirror) (2)(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class BearingCapMK3V3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'Bearing_Cap_MK3 v3'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class PCBConnectorV4(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'PCB_Connector v4'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RTAPNoSensorV12(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'R-T-AP-NoSensor v12'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part4x8x3V3Mirror(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '4x8x3 v3(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class TTPExpV52(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'T-TP-Exp v52'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part4x8x3V3_2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '4x8x3 v3'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RPPPV22(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'R-P-PP v22'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part4x8x3V3Mirror_2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '4x8x3 v3(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class PPPSkinV2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'P-PP-Skin v2'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class TDPSkinV24(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'T-DP-Skin v24'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RTDPNoSensorV19(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'R-T-DP-NoSensor v19'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part4x8x3V3Mirror_3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '4x8x3 v3(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RPPPV22_2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'R-P-PP v22'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part4x8x3V3Mirror_4(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '4x8x3 v3(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class PPPSkinV2_2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'P-PP-Skin v2'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RAPNoSensorV13(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'R-AP-NoSensor v13'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part4x8x3V3Mirror_5(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '4x8x3 v3(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DPFreeV10(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DP-Free v10'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RIPV50(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'R-IP v50'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DPSkinRoundV47(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DP-Skin-Round v47'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part4x8x3V3Mirror_6(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '4x8x3 v3(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RMPPV22(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'R-M-PP v22'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part4x8x3V3Mirror_7(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '4x8x3 v3(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class MPPSkinV39(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'M-PP-Skin v39'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DPSkinRoundV47_2(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DP-Skin-Round v47'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DPSkinRoundV47_3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DP-Skin-Round v47'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RIPPV44(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'R-I-PP v44'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part4x8x3V3Mirror_8(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '4x8x3 v3(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class IPPSkinV3(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'I-PP-Skin v3'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RAPNoSensorV17(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'R-AP-NoSensor v17'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part4x8x3V3Mirror_9(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '4x8x3 v3(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class RIPV49(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'R-IP v49'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class DPSkinRoundV46(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'DP-Skin-Round v46'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class Part4x8x3V3Mirror_10(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = '4x8x3 v3(Mirror)'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class WristBearringV1(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'WristBearring v1'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5


class TableTennisV4(StepNode):

    step_source = '../../orca_v1/ORCA_Assembly/ORCA_v1.step'
    part = 'TableTennis v4'

    # A vendor document is fillets and threads; the framework's
    # 0.1 rad default costs an order of magnitude in artifact
    # size (19.91 MB against 1.76 MB measured on one part).
    angular_deflection = 0.5
